config:
  credentials: []
  project_repos:
    git.scc.kit.edu/synergy.o3as/o3api:
      branch: master
      repo: https://git.scc.kit.edu/synergy.o3as/o3api
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      git.scc.kit.edu/synergy.o3as/o3api git:
        commands:
        - /usr/bin/env sh .sqa/script.beady-seashell-urchin.sh
        container: qc.acc_craggy-lime-barb
  QC.Doc:
    repos:
      git.scc.kit.edu/synergy.o3as/o3api find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-dandelion-shark.sh
        container: qc.doc_smelly-sepia-koala
      git.scc.kit.edu/synergy.o3as/o3api git:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-chocolate-maltese.sh
        container: qc.doc_pretty-vermilion-magpie
      git.scc.kit.edu/synergy.o3as/o3api markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-salmon-forest.sh
        container: qc.doc_droopy-azure-mouse
      git.scc.kit.edu/synergy.o3as/o3api restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-pear-millipede.sh
        container: qc.doc_smelly-heliotrope-hound
  QC.Lic:
    repos:
      git.scc.kit.edu/synergy.o3as/o3api licensee:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-purple-gharial.sh
        container: qc.lic_skimpy-beige-discus
  QC.Sec:
    repos:
      git.scc.kit.edu/synergy.o3as/o3api bandit:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-lime-cuttlefish.sh
        container: qc.sec_goopy-peach-dogfish
  QC.Sty:
    repos:
      git.scc.kit.edu/synergy.o3as/o3api flake8:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-smalt-affenpinscher.sh
        container: qc.sty_clammy-khaki-frise
      git.scc.kit.edu/synergy.o3as/o3api hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-coral-quokka.sh
        container: qc.sty_boozy-azure-albatross
  QC.Ver:
    repos:
      git.scc.kit.edu/synergy.o3as/o3api get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-puce-catfish.sh
        container: qc.ver_shaky-brass-blue
timeout: 1800
