config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.3.0-alpha1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/o3api:
      repo: https://github.com/eosc-synergy/o3api
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-synergy/o3api git:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-goldenrod-frog.sh
        container: qc.acc_skinny-linen-kakapo
  QC.Doc:
    repos:
      github.com/eosc-synergy/o3api find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-copper-chameleon.sh
        container: qc.doc_fuzzy-amethyst-lion
      github.com/eosc-synergy/o3api markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-maroon-loon.sh
        container: qc.doc_homey-zucchini-mammoth
      github.com/eosc-synergy/o3api restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-gold-goose.sh
        container: qc.doc_wimpy-goldenrod-dunker
  QC.Lic:
    repos:
      github.com/eosc-synergy/o3api licensee:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-cerise-pig.sh
        container: qc.lic_hazy-black-beetle
  QC.Sec:
    repos:
      github.com/eosc-synergy/o3api bandit:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-goldenrod-woodlouse.sh
        container: qc.sec_homely-khaki-butterfly
  QC.Sty:
    repos:
      github.com/eosc-synergy/o3api flake8:
        commands:
        - /usr/bin/env sh .sqa/script.homey-blue-gibbon.sh
        container: qc.sty_silly-zucchini-beagle
timeout: 600
