config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/o3api:
      branch: master
      repo: https://github.com/EOSC-synergy/o3api
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/o3api git:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-flax-bonobo.sh
        container: qc.acc_beady-flax-axolotl
  QC.Doc:
    repos:
      github.com/EOSC-synergy/o3api find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.homely-tomato-kingfisher.sh
        container: qc.doc_muggy-ultramarine-bullfrog
      github.com/EOSC-synergy/o3api git:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-sepia-argentino.sh
        container: qc.doc_baggy-ultramarine-crab
      github.com/EOSC-synergy/o3api markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-maroon-monster.sh
        container: qc.doc_baggy-green-nightingale
      github.com/EOSC-synergy/o3api restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-cinnabar-gopher.sh
        container: qc.doc_blurry-cinnamon-skunk
  QC.Lic:
    repos:
      github.com/EOSC-synergy/o3api licensee:
        commands:
        - /usr/bin/env sh .sqa/script.silly-ochre-paradise.sh
        container: qc.lic_zippy-gamboge-wolf
  QC.Met:
    repos:
      github.com/EOSC-synergy/o3api validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-silver-zebra.sh
        container: qc.met_wheezy-pumpkin-bonobo
  QC.Sec:
    repos:
      github.com/EOSC-synergy/o3api bandit:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-aquamarine-lobster.sh
        container: qc.sec_nerdy-fuchsia-angelfish
  QC.Sty:
    repos:
      github.com/EOSC-synergy/o3api flake8:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-sepia-mongrel.sh
        container: qc.sty_clammy-denim-warthog
      github.com/EOSC-synergy/o3api hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-ecru-squirrel.sh
        container: qc.sty_scummy-cinnamon-snake
      github.com/EOSC-synergy/o3api jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-burgundy-bulldog.sh
        container: qc.sty_trippy-indigo-buffalo
  QC.Ver:
    repos:
      github.com/EOSC-synergy/o3api get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-harlequin-mist.sh
        container: qc.ver_homely-mauve-chinchilla
timeout: 1800
