config:
  credentials: []
  project_repos:
    git.scc.kit.edu/synergy.o3as/o3api:
      branch: master
      repo: https://git.scc.kit.edu/synergy.o3as/o3api
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      git.scc.kit.edu/synergy.o3as/o3api git:
        commands:
        - /usr/bin/env sh .sqa/script.homely-purple-gorilla.sh
        container: qc.acc_ugly-ivory-caracal
  QC.Doc:
    repos:
      git.scc.kit.edu/synergy.o3as/o3api find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-copper-monkey.sh
        container: qc.doc_scanty-ecru-macaque
      git.scc.kit.edu/synergy.o3as/o3api git:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-carmine-falcon.sh
        container: qc.doc_beady-vermilion-jellyfish
      git.scc.kit.edu/synergy.o3as/o3api markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-purple-hamster.sh
        container: qc.doc_hilly-ultramarine-civet
      git.scc.kit.edu/synergy.o3as/o3api restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-harlequin-gecko.sh
        container: qc.doc_baggy-heliotrope-jackal
  QC.Lic:
    repos:
      git.scc.kit.edu/synergy.o3as/o3api licensee:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-maroon-ostrich.sh
        container: qc.lic_foggy-ecru-saola
  QC.Met:
    repos:
      git.scc.kit.edu/synergy.o3as/o3api cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-puce-cow.sh
        container: qc.met_tasty-rose-snail
      git.scc.kit.edu/synergy.o3as/o3api validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-tomato-leopard.sh
        container: qc.met_snazzy-myrtle-otter
  QC.Sec:
    repos:
      git.scc.kit.edu/synergy.o3as/o3api bandit:
        commands:
        - /usr/bin/env sh .sqa/script.homely-olive-wasp.sh
        container: qc.sec_ready-chestnut-frog
  QC.Sty:
    repos:
      git.scc.kit.edu/synergy.o3as/o3api flake8:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-razzmatazz-dragon.sh
        container: qc.sty_lousy-red-molly
      git.scc.kit.edu/synergy.o3as/o3api hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-fuchsia-macaque.sh
        container: qc.sty_woozy-pink-javanese
      git.scc.kit.edu/synergy.o3as/o3api jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-tomato-pinscher.sh
        container: qc.sty_nerdy-pink-walrus
  QC.Ver:
    repos:
      git.scc.kit.edu/synergy.o3as/o3api get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-cinnabar-malamute.sh
        container: qc.ver_thirsty-saffron-spider
timeout: 5400
