config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/o3api:
      branch: master
      repo: https://github.com/EOSC-synergy/o3api
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.7.0_no_kubectl
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/o3api git:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-violet-javanese.sh
        container: qc.acc_skanky-cream-avocet
  QC.Doc:
    repos:
      github.com/EOSC-synergy/o3api find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-carmine-bee.sh
        container: qc.doc_geeky-aqua-cougar
      github.com/EOSC-synergy/o3api git:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-cinnabar-argentino.sh
        container: qc.doc_snazzy-saffron-bracke
      github.com/EOSC-synergy/o3api markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-carmine-setter.sh
        container: qc.doc_cheeky-ruby-goose
      github.com/EOSC-synergy/o3api restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-burgundy-cockroach.sh
        container: qc.doc_pretty-seashell-ray
  QC.FAIR:
    repos:
      github.com/EOSC-synergy/o3api F-UJI:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-celadon-barnacle.sh
        container: qc.fair_flimsy-taupe-cichlid
  QC.Lic:
    repos:
      github.com/EOSC-synergy/o3api licensee:
        commands:
        - /usr/bin/env sh .sqa/script.randy-cinnamon-flamingo.sh
        container: qc.lic_wiggy-lemon-scorpion
  QC.Sec:
    repos:
      github.com/EOSC-synergy/o3api bandit:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-jade-capuchin.sh
        container: qc.sec_crappy-saffron-mau
  QC.Sty:
    repos:
      github.com/EOSC-synergy/o3api flake8:
        commands:
        - /usr/bin/env sh .sqa/script.surly-blue-akbash.sh
        container: qc.sty_beady-heliotrope-spider
  QC.Ver:
    repos:
      github.com/EOSC-synergy/o3api get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-chestnut-orangutan.sh
        container: qc.ver_snoopy-olivine-panda
timeout: 1800
