config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/o3api:
      branch: master
      repo: https://github.com/EOSC-synergy/o3api
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/o3api git:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-apricot-devil.sh
        container: qc.acc_dorky-cinnabar-goose
  QC.Doc:
    repos:
      github.com/EOSC-synergy/o3api find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-cinnamon-caterpillar.sh
        container: qc.doc_breezy-viridian-centipede
      github.com/EOSC-synergy/o3api git:
        commands:
        - /usr/bin/env sh .sqa/script.messy-rose-warthog.sh
        container: qc.doc_wheezy-crimson-kakapo
      github.com/EOSC-synergy/o3api markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-chocolate-saola.sh
        container: qc.doc_chummy-russet-bandicoot
      github.com/EOSC-synergy/o3api restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-cardinal-eleuth.sh
        container: qc.doc_whiny-ochre-crocodile
  QC.Lic:
    repos:
      github.com/EOSC-synergy/o3api licensee:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-chocolate-squirt.sh
        container: qc.lic_silly-blue-beetle
  QC.Met:
    repos:
      github.com/EOSC-synergy/o3api cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-cerise-quetzal.sh
        container: qc.met_gloppy-malachite-chicken
      github.com/EOSC-synergy/o3api validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-amber-squid.sh
        container: qc.met_flaky-fuchsia-chinchilla
  QC.Sec:
    repos:
      github.com/EOSC-synergy/o3api bandit:
        commands:
        - /usr/bin/env sh .sqa/script.silly-wisteria-wolverine.sh
        container: qc.sec_woozy-goldenrod-bonobo
  QC.Sty:
    repos:
      github.com/EOSC-synergy/o3api flake8:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-cinnamon-gibbon.sh
        container: qc.sty_sleepy-sangria-yak
      github.com/EOSC-synergy/o3api hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-platinum-maltese.sh
        container: qc.sty_chewy-charcoal-liger
      github.com/EOSC-synergy/o3api jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-black-forest.sh
        container: qc.sty_woolly-rust-husky
  QC.Ver:
    repos:
      github.com/EOSC-synergy/o3api get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-brass-maltese.sh
        container: qc.ver_hilly-sepia-frigatebird
timeout: 5400
