config:
  credentials: []
  project_repos:
    git.scc.kit.edu/synergy.o3as/o3api:
      branch: master
      repo: https://git.scc.kit.edu/synergy.o3as/o3api
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.7.0_no_kubectl
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      git.scc.kit.edu/synergy.o3as/o3api git:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-lavender-kakapo.sh
        container: qc.acc_crappy-auburn-lynx
  QC.Doc:
    repos:
      git.scc.kit.edu/synergy.o3as/o3api find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-crimson-dachshund.sh
        container: qc.doc_snippy-corn-budgerigar
      git.scc.kit.edu/synergy.o3as/o3api git:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-taupe-hare.sh
        container: qc.doc_nerdy-coral-tarsier
      git.scc.kit.edu/synergy.o3as/o3api markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-zucchini-corgi.sh
        container: qc.doc_woolly-gold-mastiff
      git.scc.kit.edu/synergy.o3as/o3api restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-thistle-uguisu.sh
        container: qc.doc_bumpy-emerald-sheep
  QC.Lic:
    repos:
      git.scc.kit.edu/synergy.o3as/o3api licensee:
        commands:
        - /usr/bin/env sh .sqa/script.surly-ultramarine-akbash.sh
        container: qc.lic_jumpy-cerise-donkey
  QC.Sec:
    repos:
      git.scc.kit.edu/synergy.o3as/o3api bandit:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-denim-ferret.sh
        container: qc.sec_beady-persimmon-kakapo
  QC.Sty:
    repos:
      git.scc.kit.edu/synergy.o3as/o3api flake8:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-coral-wolf.sh
        container: qc.sty_muzzy-wisteria-shark
  QC.Ver:
    repos:
      git.scc.kit.edu/synergy.o3as/o3api get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-magnolia-duck.sh
        container: qc.ver_homey-tomato-sparrow
timeout: 1800
