config:
  credentials: []
  project_repos:
    git.scc.kit.edu/synergy.o3as/o3api:
      branch: master
      repo: https://git.scc.kit.edu/synergy.o3as/o3api
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.7.0_no_kubectl
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      git.scc.kit.edu/synergy.o3as/o3api git:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-cerise-monster.sh
        container: qc.acc_beady-turquoise-saola
  QC.Doc:
    repos:
      git.scc.kit.edu/synergy.o3as/o3api find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-lilac-ragdoll.sh
        container: qc.doc_sickly-cinnabar-maltese
      git.scc.kit.edu/synergy.o3as/o3api git:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-tan-wasp.sh
        container: qc.doc_gamy-chocolate-antelope
      git.scc.kit.edu/synergy.o3as/o3api markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-malachite-warthog.sh
        container: qc.doc_gamy-persimmon-okapi
      git.scc.kit.edu/synergy.o3as/o3api restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-puce-vole.sh
        container: qc.doc_crappy-maroon-squirt
  QC.FAIR:
    repos:
      git.scc.kit.edu/synergy.o3as/o3api F-UJI:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-crimson-falcon.sh
        container: qc.fair_stuffy-dandelion-blue
  QC.Lic:
    repos:
      git.scc.kit.edu/synergy.o3as/o3api licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-lime-setter.sh
        container: qc.lic_flabby-wisteria-coral
  QC.Sec:
    repos:
      git.scc.kit.edu/synergy.o3as/o3api bandit:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-mauve-kakapo.sh
        container: qc.sec_shabby-auburn-bullfrog
  QC.Sty:
    repos:
      git.scc.kit.edu/synergy.o3as/o3api flake8:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-viridian-grasshopper.sh
        container: qc.sty_wheezy-orchid-hummingbird
  QC.Ver:
    repos:
      git.scc.kit.edu/synergy.o3as/o3api get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-lime-chin.sh
        container: qc.ver_pretty-indigo-cattle
timeout: 1800
