config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/o3api:
      branch: master
      repo: https://github.com/EOSC-synergy/o3api
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.7.0_no_kubectl
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/o3api git:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-mustard-bloodhound.sh
        container: qc.acc_cozy-ochre-squirrel
  QC.Doc:
    repos:
      github.com/EOSC-synergy/o3api find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-razzmatazz-squirrel.sh
        container: qc.doc_sunny-violet-dodo
      github.com/EOSC-synergy/o3api git:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-wisteria-discus.sh
        container: qc.doc_droopy-tan-wombat
      github.com/EOSC-synergy/o3api markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-amethyst-okapi.sh
        container: qc.doc_queasy-cerise-alligator
      github.com/EOSC-synergy/o3api restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-orange-lionfish.sh
        container: qc.doc_chummy-harlequin-toad
  QC.FAIR:
    repos:
      github.com/EOSC-synergy/o3api F-UJI:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-olivine-kangaroo.sh
        container: qc.fair_crabby-crimson-mayfly
  QC.Lic:
    repos:
      github.com/EOSC-synergy/o3api licensee:
        commands:
        - /usr/bin/env sh .sqa/script.silly-platinum-tarsier.sh
        container: qc.lic_paltry-amethyst-cattle
  QC.Sec:
    repos:
      github.com/EOSC-synergy/o3api bandit:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-brown-squirt.sh
        container: qc.sec_pokey-olivine-eagle
  QC.Sty:
    repos:
      github.com/EOSC-synergy/o3api flake8:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-bronze-butterfly.sh
        container: qc.sty_flaky-pink-sheepdog
  QC.Ver:
    repos:
      github.com/EOSC-synergy/o3api get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-rose-jellyfish.sh
        container: qc.ver_hasty-ecru-rottweiler
timeout: 1800
