config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.7.0-only_im_client
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/o3api:
      branch: master
      repo: https://github.com/eosc-synergy/o3api
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-synergy/o3api git:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-cerulean-olm.sh
        container: qc.acc_dorky-grey-tarantula
  QC.Doc:
    repos:
      github.com/eosc-synergy/o3api find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-puce-argentino.sh
        container: qc.doc_stuffy-magnolia-dogfish
      github.com/eosc-synergy/o3api git:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-xanthic-gar.sh
        container: qc.doc_pokey-heliotrope-greyhound
      github.com/eosc-synergy/o3api markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-grey-olm.sh
        container: qc.doc_woozy-cerise-malamute
      github.com/eosc-synergy/o3api restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-firebrick-chameleon.sh
        container: qc.doc_sickly-cardinal-gibbon
  QC.FAIR:
    repos:
      github.com/eosc-synergy/o3api F-UJI:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-russet-swan.sh
        container: qc.fair_queasy-brass-hippopotamus
  QC.Lic:
    repos:
      github.com/eosc-synergy/o3api licensee:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-emerald-newfoundland.sh
        container: qc.lic_squeaky-maroon-ocelot
  QC.Sec:
    repos:
      github.com/eosc-synergy/o3api bandit:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-ecru-spoonbill.sh
        container: qc.sec_grumpy-russet-gecko
  QC.Sty:
    repos:
      github.com/eosc-synergy/o3api flake8:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-cyan-cat.sh
        container: qc.sty_paltry-blue-dragon
  QC.Ver:
    repos:
      github.com/eosc-synergy/o3api get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.randy-chartreuse-fowl.sh
        container: qc.ver_ugly-indigo-owl
timeout: 1800
