config:
  credentials: []
  project_repos:
    git.scc.kit.edu/synergy.o3as/o3api:
      branch: master
      repo: https://git.scc.kit.edu/synergy.o3as/o3api
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      git.scc.kit.edu/synergy.o3as/o3api git:
        commands:
        - /usr/bin/env sh .sqa/script.homey-linen-loon.sh
        container: qc.acc_bumpy-corn-greyhound
  QC.Doc:
    repos:
      git.scc.kit.edu/synergy.o3as/o3api find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-smalt-armadillo.sh
        container: qc.doc_seedy-vermilion-urchin
      git.scc.kit.edu/synergy.o3as/o3api git:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-tangerine-wolfhound.sh
        container: qc.doc_slaphappy-chartreuse-spitz
      git.scc.kit.edu/synergy.o3as/o3api markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-coral-squirt.sh
        container: qc.doc_sleepy-amethyst-orangutan
      git.scc.kit.edu/synergy.o3as/o3api restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-wisteria-moorhen.sh
        container: qc.doc_gummy-jade-zorse
  QC.Lic:
    repos:
      git.scc.kit.edu/synergy.o3as/o3api licensee:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-ivory-shark.sh
        container: qc.lic_muzzy-smalt-raccoon
  QC.Met:
    repos:
      git.scc.kit.edu/synergy.o3as/o3api cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-dandelion-mongoose.sh
        container: qc.met_blurry-aqua-millipede
      git.scc.kit.edu/synergy.o3as/o3api validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.homey-sapphire-kangaroo.sh
        container: qc.met_skinny-buff-owl
  QC.Sec:
    repos:
      git.scc.kit.edu/synergy.o3as/o3api bandit:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-blue-rat.sh
        container: qc.sec_leaky-burgundy-lion
  QC.Sty:
    repos:
      git.scc.kit.edu/synergy.o3as/o3api flake8:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-scarlet-coyote.sh
        container: qc.sty_cozy-ultramarine-cat
      git.scc.kit.edu/synergy.o3as/o3api hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-scarlet-capuchin.sh
        container: qc.sty_ready-lavender-ocelot
      git.scc.kit.edu/synergy.o3as/o3api jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.surly-pink-quoll.sh
        container: qc.sty_scummy-amethyst-binturong
  QC.Ver:
    repos:
      git.scc.kit.edu/synergy.o3as/o3api get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-bistre-donkey.sh
        container: qc.ver_snippy-red-mandrill
timeout: 5400
