config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.3.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/o3api:
      repo: https://github.com/eosc-synergy/o3api
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-synergy/o3api git:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-periwinkle-shrew.sh
        container: qc.acc_ugly-platinum-capybara
  QC.Doc:
    repos:
      github.com/eosc-synergy/o3api find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-saffron-husky.sh
        container: qc.doc_chewy-charcoal-discus
      github.com/eosc-synergy/o3api markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-ecru-wallaby.sh
        container: qc.doc_boozy-charcoal-giraffe
      github.com/eosc-synergy/o3api restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-chocolate-uguisu.sh
        container: qc.doc_woozy-amber-gibbon
  QC.Lic:
    repos:
      github.com/eosc-synergy/o3api licensee:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-gold-squid.sh
        container: qc.lic_trippy-cinnamon-cuttlefish
  QC.Sec:
    repos:
      github.com/eosc-synergy/o3api bandit:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-violet-jaguar.sh
        container: qc.sec_sleazy-cinnamon-rat
  QC.Sty:
    repos:
      github.com/eosc-synergy/o3api flake8:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-cobalt-bobcat.sh
        container: qc.sty_homely-cream-hare
timeout: 600
