config:
  credentials: []
  project_repos:
    git.scc.kit.edu/synergy.o3as/o3api:
      branch: master
      repo: https://git.scc.kit.edu/synergy.o3as/o3api
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      git.scc.kit.edu/synergy.o3as/o3api git:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-brass-mandrill.sh
        container: qc.acc_skimpy-aqua-warthog
  QC.Doc:
    repos:
      git.scc.kit.edu/synergy.o3as/o3api find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-yellow-ray.sh
        container: qc.doc_bluesy-orange-malamute
      git.scc.kit.edu/synergy.o3as/o3api git:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-flax-hippopotamus.sh
        container: qc.doc_shaky-ultramarine-olm
      git.scc.kit.edu/synergy.o3as/o3api markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-wheat-ant.sh
        container: qc.doc_sunny-azure-zorse
      git.scc.kit.edu/synergy.o3as/o3api restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-puce-barnacle.sh
        container: qc.doc_leaky-buff-caracal
  QC.Lic:
    repos:
      git.scc.kit.edu/synergy.o3as/o3api licensee:
        commands:
        - /usr/bin/env sh .sqa/script.beady-apricot-ibis.sh
        container: qc.lic_jumpy-asparagus-maltese
  QC.Sec:
    repos:
      git.scc.kit.edu/synergy.o3as/o3api bandit:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-asparagus-tang.sh
        container: qc.sec_cloudy-charcoal-greyhound
  QC.Sty:
    repos:
      git.scc.kit.edu/synergy.o3as/o3api flake8:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-purple-zebra.sh
        container: qc.sty_ugly-flax-donkey
      git.scc.kit.edu/synergy.o3as/o3api hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-cobalt-weasel.sh
        container: qc.sty_bumpy-azure-gibbon
  QC.Ver:
    repos:
      git.scc.kit.edu/synergy.o3as/o3api get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-periwinkle-grouse.sh
        container: qc.ver_pretty-harlequin-moorhen
timeout: 1800
