config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/o3api:
      branch: master
      repo: https://github.com/EOSC-synergy/o3api
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/o3api git:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-cardinal-duck.sh
        container: qc.acc_crabby-khaki-bullfrog
  QC.Doc:
    repos:
      github.com/EOSC-synergy/o3api find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-magnolia-uguisu.sh
        container: qc.doc_sickly-rust-sloth
      github.com/EOSC-synergy/o3api git:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-emerald-manatee.sh
        container: qc.doc_whiny-taupe-chow
      github.com/EOSC-synergy/o3api markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-orchid-baboon.sh
        container: qc.doc_hilly-chartreuse-affenpinscher
      github.com/EOSC-synergy/o3api restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-tan-skunk.sh
        container: qc.doc_stealthy-copper-lemming
  QC.Lic:
    repos:
      github.com/EOSC-synergy/o3api licensee:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-russet-birman.sh
        container: qc.lic_hasty-ivory-kakapo
  QC.Met:
    repos:
      github.com/EOSC-synergy/o3api validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-gamboge-tamarin.sh
        container: qc.met_homely-salmon-moose
  QC.Sec:
    repos:
      github.com/EOSC-synergy/o3api bandit:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-russet-tortoise.sh
        container: qc.sec_flabby-chestnut-snail
  QC.Sty:
    repos:
      github.com/EOSC-synergy/o3api flake8:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-cinnabar-jellyfish.sh
        container: qc.sty_homely-green-goat
      github.com/EOSC-synergy/o3api hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-periwinkle-bandicoot.sh
        container: qc.sty_hilly-aqua-tzu
      github.com/EOSC-synergy/o3api jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-tangerine-crocodile.sh
        container: qc.sty_tacky-amaranth-retriever
  QC.Ver:
    repos:
      github.com/EOSC-synergy/o3api get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-cardinal-hyrax.sh
        container: qc.ver_bumpy-heliotrope-ferret
timeout: 1800
