config:
  credentials: []
  project_repos:
    git.scc.kit.edu/synergy.o3as/o3api:
      branch: master
      repo: https://git.scc.kit.edu/synergy.o3as/o3api
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      git.scc.kit.edu/synergy.o3as/o3api git:
        commands:
        - /usr/bin/env sh .sqa/script.homely-coral-coati.sh
        container: qc.acc_lovely-salmon-grouse
  QC.Doc:
    repos:
      git.scc.kit.edu/synergy.o3as/o3api find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-flax-monster.sh
        container: qc.doc_smelly-persimmon-deer
      git.scc.kit.edu/synergy.o3as/o3api git:
        commands:
        - /usr/bin/env sh .sqa/script.homely-champagne-capuchin.sh
        container: qc.doc_skimpy-tangerine-wolverine
      git.scc.kit.edu/synergy.o3as/o3api markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.surly-sepia-kiwi.sh
        container: qc.doc_gloppy-zucchini-serval
      git.scc.kit.edu/synergy.o3as/o3api restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-pumpkin-turkey.sh
        container: qc.doc_stuffy-cerulean-anteater
  QC.Lic:
    repos:
      git.scc.kit.edu/synergy.o3as/o3api licensee:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-rose-foxhound.sh
        container: qc.lic_whiny-mustard-mau
  QC.Sec:
    repos:
      git.scc.kit.edu/synergy.o3as/o3api bandit:
        commands:
        - /usr/bin/env sh .sqa/script.homely-plum-tarantula.sh
        container: qc.sec_flaky-peach-bison
  QC.Sty:
    repos:
      git.scc.kit.edu/synergy.o3as/o3api flake8:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-orange-squid.sh
        container: qc.sty_stinky-ivory-zonkey
      git.scc.kit.edu/synergy.o3as/o3api hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-seashell-tapir.sh
        container: qc.sty_ugly-cornflower-oriole
  QC.Ver:
    repos:
      git.scc.kit.edu/synergy.o3as/o3api get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-rose-drever.sh
        container: qc.ver_gamy-cyan-bullfrog
timeout: 1800
