config:
  credentials: []
  project_repos:
    git.scc.kit.edu/synergy.o3as/o3api:
      branch: master
      repo: https://git.scc.kit.edu/synergy.o3as/o3api
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.6
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      git.scc.kit.edu/synergy.o3as/o3api git:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-red-bison.sh
        container: qc.acc_woolly-cinnamon-woodpecker
  QC.Doc:
    repos:
      git.scc.kit.edu/synergy.o3as/o3api find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-ultramarine-bat.sh
        container: qc.doc_cranky-ecru-albatross
      git.scc.kit.edu/synergy.o3as/o3api git:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-sepia-raccoon.sh
        container: qc.doc_scanty-heliotrope-worm
      git.scc.kit.edu/synergy.o3as/o3api markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.ready-cinnabar-hyena.sh
        container: qc.doc_seedy-lime-urchin
      git.scc.kit.edu/synergy.o3as/o3api restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.homey-xanthic-serval.sh
        container: qc.doc_crabby-russet-bee
  QC.Lic:
    repos:
      git.scc.kit.edu/synergy.o3as/o3api licensee:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-lavender-bombay.sh
        container: qc.lic_sleepy-olivine-goose
  QC.Met:
    repos:
      git.scc.kit.edu/synergy.o3as/o3api validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-carmine-tuatara.sh
        container: qc.met_bumpy-denim-donkey
  QC.Sec:
    repos:
      git.scc.kit.edu/synergy.o3as/o3api bandit:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-pear-chinchilla.sh
        container: qc.sec_cranky-tomato-dunker
  QC.Sty:
    repos:
      git.scc.kit.edu/synergy.o3as/o3api flake8:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-bistre-burmese.sh
        container: qc.sty_squeaky-crimson-wolverine
      git.scc.kit.edu/synergy.o3as/o3api hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-wisteria-wallaby.sh
        container: qc.sty_chewy-apricot-gibbon
      git.scc.kit.edu/synergy.o3as/o3api jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-chocolate-cuscus.sh
        container: qc.sty_sleepy-crimson-harrier
  QC.Ver:
    repos:
      git.scc.kit.edu/synergy.o3as/o3api get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-khaki-bird.sh
        container: qc.ver_jumpy-malachite-fousek
timeout: 1800
