config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/o3api:
      branch: master
      repo: https://github.com/EOSC-synergy/o3api
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.7.0-only_im_client
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/o3api git:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-peach-raccoon.sh
        container: qc.acc_messy-tomato-tzu
  QC.Doc:
    repos:
      github.com/EOSC-synergy/o3api find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-cardinal-owl.sh
        container: qc.doc_stuffy-cinnamon-rottweiler
      github.com/EOSC-synergy/o3api git:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-purple-duck.sh
        container: qc.doc_tasty-gold-stingray
      github.com/EOSC-synergy/o3api markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-violet-hamster.sh
        container: qc.doc_queasy-violet-bear
      github.com/EOSC-synergy/o3api restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-aqua-hyrax.sh
        container: qc.doc_cloudy-wheat-malamute
  QC.FAIR:
    repos:
      github.com/EOSC-synergy/o3api F-UJI:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-puce-echidna.sh
        container: qc.fair_slimy-apricot-meerkat
  QC.Lic:
    repos:
      github.com/EOSC-synergy/o3api licensee:
        commands:
        - /usr/bin/env sh .sqa/script.beady-cream-cow.sh
        container: qc.lic_beady-turquoise-zebu
  QC.Sec:
    repos:
      github.com/EOSC-synergy/o3api bandit:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-alizarin-cichlid.sh
        container: qc.sec_leaky-ochre-gibbon
  QC.Sty:
    repos:
      github.com/EOSC-synergy/o3api flake8:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-crimson-lobster.sh
        container: qc.sty_goopy-taupe-mastiff
  QC.Ver:
    repos:
      github.com/EOSC-synergy/o3api get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-ecru-mole.sh
        container: qc.ver_surly-turquoise-devil
timeout: 1800
