config:
  credentials: []
  project_repos:
    git.scc.kit.edu/synergy.o3as/o3api:
      branch: master
      repo: https://git.scc.kit.edu/synergy.o3as/o3api
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      git.scc.kit.edu/synergy.o3as/o3api git:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-sangria-tortoise.sh
        container: qc.acc_baggy-amethyst-grasshopper
  QC.Doc:
    repos:
      git.scc.kit.edu/synergy.o3as/o3api find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-teal-barracuda.sh
        container: qc.doc_boozy-champagne-goat
      git.scc.kit.edu/synergy.o3as/o3api git:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-vermilion-goose.sh
        container: qc.doc_shaky-asparagus-gar
      git.scc.kit.edu/synergy.o3as/o3api markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-burgundy-zebra.sh
        container: qc.doc_frumpy-alizarin-fox
      git.scc.kit.edu/synergy.o3as/o3api restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.homey-turquoise-saola.sh
        container: qc.doc_flimsy-chartreuse-bear
  QC.Lic:
    repos:
      git.scc.kit.edu/synergy.o3as/o3api licensee:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-fuchsia-slug.sh
        container: qc.lic_paltry-purple-coyote
  QC.Met:
    repos:
      git.scc.kit.edu/synergy.o3as/o3api validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-cream-wolf.sh
        container: qc.met_woolly-fuchsia-audemer
  QC.Sec:
    repos:
      git.scc.kit.edu/synergy.o3as/o3api bandit:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-ochre-wolfhound.sh
        container: qc.sec_greasy-persimmon-tortoise
  QC.Sty:
    repos:
      git.scc.kit.edu/synergy.o3as/o3api flake8:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-aquamarine-mongoose.sh
        container: qc.sty_skinny-yellow-wallaby
      git.scc.kit.edu/synergy.o3as/o3api hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-yellow-bobcat.sh
        container: qc.sty_craggy-periwinkle-rattlesnake
      git.scc.kit.edu/synergy.o3as/o3api jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-olivine-angelfish.sh
        container: qc.sty_muggy-cream-cattle
  QC.Ver:
    repos:
      git.scc.kit.edu/synergy.o3as/o3api get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-magnolia-lemming.sh
        container: qc.ver_skanky-smalt-collie
timeout: 1800
