config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/o3api:
      branch: master
      repo: https://github.com/EOSC-synergy/o3api
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.7.0-only_im_client
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/o3api git:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-pink-moth.sh
        container: qc.acc_sleazy-red-barracuda
  QC.Doc:
    repos:
      github.com/EOSC-synergy/o3api find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-cream-bee.sh
        container: qc.doc_snippy-orange-chinchilla
      github.com/EOSC-synergy/o3api git:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-fuchsia-lynx.sh
        container: qc.doc_droopy-puce-anteater
      github.com/EOSC-synergy/o3api markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-emerald-dragonfly.sh
        container: qc.doc_stinky-amber-bloodhound
      github.com/EOSC-synergy/o3api restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-ivory-flounder.sh
        container: qc.doc_snappy-wisteria-harrier
  QC.FAIR:
    repos:
      github.com/EOSC-synergy/o3api F-UJI:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-coral-chinook.sh
        container: qc.fair_wheezy-azure-bird
  QC.Lic:
    repos:
      github.com/EOSC-synergy/o3api licensee:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-cyan-hornet.sh
        container: qc.lic_boozy-chocolate-kangaroo
  QC.Sec:
    repos:
      github.com/EOSC-synergy/o3api bandit:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-magnolia-chameleon.sh
        container: qc.sec_chewy-ecru-malamute
  QC.Sty:
    repos:
      github.com/EOSC-synergy/o3api flake8:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-plum-salamander.sh
        container: qc.sty_wheezy-amaranth-duck
  QC.Ver:
    repos:
      github.com/EOSC-synergy/o3api get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-eggplant-skunk.sh
        container: qc.ver_surly-alizarin-coral
timeout: 1800
