config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/o3api:
      branch: master
      repo: https://github.com/EOSC-synergy/o3api
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/o3api git:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-indigo-hyrax.sh
        container: qc.acc_wheezy-scarlet-chicken
  QC.Doc:
    repos:
      github.com/EOSC-synergy/o3api find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-magnolia-owl.sh
        container: qc.doc_hazy-violet-cuscus
      github.com/EOSC-synergy/o3api git:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-cobalt-caterpillar.sh
        container: qc.doc_greasy-ecru-turkey
      github.com/EOSC-synergy/o3api markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-brown-seal.sh
        container: qc.doc_tasty-viridian-numbat
      github.com/EOSC-synergy/o3api restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-platinum-dane.sh
        container: qc.doc_stuffy-tangerine-boar
  QC.Lic:
    repos:
      github.com/EOSC-synergy/o3api licensee:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-smalt-frise.sh
        container: qc.lic_lumpy-yellow-zebu
  QC.Met:
    repos:
      github.com/EOSC-synergy/o3api validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-russet-dane.sh
        container: qc.met_stuffy-crimson-gopher
  QC.Sec:
    repos:
      github.com/EOSC-synergy/o3api bandit:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-maroon-dugong.sh
        container: qc.sec_pokey-ecru-horse
  QC.Sty:
    repos:
      github.com/EOSC-synergy/o3api flake8:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-purple-rhinoceros.sh
        container: qc.sty_droopy-persimmon-sloth
      github.com/EOSC-synergy/o3api hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-black-buffalo.sh
        container: qc.sty_hilly-purple-argentino
      github.com/EOSC-synergy/o3api jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-cobalt-robin.sh
        container: qc.sty_foggy-green-dogfish
  QC.Ver:
    repos:
      github.com/EOSC-synergy/o3api get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-brass-argentino.sh
        container: qc.ver_freaky-zucchini-vole
timeout: 1800
