config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/o3api:
      repo: https://github.com/EOSC-synergy/o3api
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.1.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/o3api git:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-malachite-blue.sh
        container: qc.acc_ugly-white-quetzal
  QC.Doc:
    repos:
      github.com/EOSC-synergy/o3api find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-amaranth-skunk.sh
        container: qc.doc_hasty-mauve-buffalo
      github.com/EOSC-synergy/o3api markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.homely-malachite-goat.sh
        container: qc.doc_craggy-grey-havanese
      github.com/EOSC-synergy/o3api restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-black-bloodhound.sh
        container: qc.doc_woozy-lime-ocelot
  QC.Lic:
    repos:
      github.com/EOSC-synergy/o3api licensee:
        commands:
        - /usr/bin/env sh .sqa/script.ready-lavender-uguisu.sh
        container: qc.lic_paltry-lavender-robin
timeout: 600
